site_name: Media-DL
site_description: Download any video/audio you want from a simple URL ✨

repo_name: rikiub/media-dl
repo_url: https://github.com/rikiub/media-dl

theme:
  name: material

  font:
    text: Rubik
    code: Fira Code

  features:
    # - navigation.tabs
    - navigation.expand
    # - navigation.sections
    - content.code.copy

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - autorefs
  - mkdocstrings
