from typing import cast, get_args, Callable, NewType, Any
from pathlib import Path
from copy import copy
import logging
import json

from yt_dlp import YoutubeDL, DownloadError
from yt_dlp.postprocessor import PostProcessor
from mutagen._file import FileType
import syncedlyrics
import music_tag

from media_dl.types import (
    Media,
    Playlist,
    ResultType,
    EXTENSION,
    EXT_VIDEO,
    EXT_AUDIO,
    QUALITY,
    QUALITY_VIDEO,
)
from media_dl.config import DIR_TEMP


fake_logger = logging.getLogger("YoutubeDL")
fake_logger.disabled = True

InfoDict = NewType("InfoDict", dict[str, Any])

_THUMB_COMPATIBLE = {
    "mp3",
    "mkv",
    "mka",
    "ogg",
    "opus",
    "flac",
    "m4a",
    "mp4",
    "mov",
}


class MusicMetaPP(PostProcessor):
    EXTS = get_args(EXT_AUDIO)

    def run(self, information):
        ext = information["ext"]
        track = information.get("track")
        artist = information.get("artist")

        if ext in self.EXTS and track and artist:
            audio = music_tag.load_file(information["filepath"])
            audio = cast(FileType, audio)

            # Fix year tag
            if not audio["year"] or len(str(audio["year"])) > 4:
                year = int(
                    information.get("release_year")
                    or information.get("upload_date")[:4]
                )
                audio["year"] = year

            if not audio["album"]:
                # Single Album
                audio["album"] = track
            if not audio["album_artist"]:
                audio["album_artist"] = artist
            if not audio["lyrics"]:
                try:
                    search_term = track + " - " + artist
                    if lyrics := syncedlyrics.search(
                        search_term, allow_plain_format=True
                    ):
                        audio["lyrics"] = lyrics
                except:
                    pass
            audio.save()

        return [], information


def get_info_thumbnail(info: InfoDict) -> str | None:
    if thumb := info.get("thumbnail"):
        return thumb
    elif thumb := info.get("thumbnails"):
        return thumb[-1]["url"]
    else:
        return None


class YDL:
    """
    Arguments:
        extension (str): Prefered file extension type.
        quality (str, int): Prefered file quality. Must be compatible with `extension`.
            Range between [1-9] for audio; Resolution [144-4320] for video.
    """

    def __init__(
        self,
        output: Path | str,
        extension: EXTENSION,
        quality: QUALITY = 9,
    ):
        self.tempdir = DIR_TEMP / "ydl"
        self.tempdir.mkdir(parents=True, exist_ok=True)
        self.outputdir = Path(output)

        opts = {
            "paths": {
                "home": str(self.outputdir),
                "temp": str(self.tempdir),
            },
            "outtmpl": "%(artist,creator,uploader)s - %(track,title)s.%(ext)s",
            "ignoreerrors": False,
            "overwrites": False,
            "quiet": True,
            "no_warnings": True,
            "extract_flat": "in_playlist",
            "logger": fake_logger,
        }
        formats = self._gen_format_opts(extension, quality)

        self._ydl = YoutubeDL(opts | formats)
        self._ydl.add_post_processor(MusicMetaPP(), when="post_process")

    def _gen_format_opts(self, extension: EXTENSION, quality: QUALITY) -> dict:
        """Generate custom YDLOpts by provided arguments.

        Args:
            extension: Wanted file extension. Custom options will be generated by the extension type.
            quality: Wanted file quality. Range between [1-9].

        Raises:
            ValueError: `extension` or `quality` is invalid.
        """
        video_args = get_args(EXT_VIDEO)
        audio_args = get_args(EXT_AUDIO)
        quality_args = get_args(QUALITY)

        if not quality in quality_args:
            raise ValueError(
                "Invalid quality range. Expected int range [1-9].",
            )

        # Prepare Options
        ydl_opts: dict = {
            "final_ext": extension,
        }
        postprocessors: list[dict] = []
        postprocessors.append(
            {"key": "FFmpegMetadata", "add_metadata": True, "add_chapters": True}
        )

        if extension in _THUMB_COMPATIBLE:
            postprocessors.append(
                {"key": "EmbedThumbnail", "already_have_thumbnail": False}
            )

        # VIDEO
        if extension in video_args:
            video_quality = get_args(QUALITY_VIDEO)[quality - 1]

            ydl_opts.update(
                {
                    "format": f"bestvideo[height<={video_quality}]+bestaudio/bestvideo[height<={video_quality}]/best",
                    "format_sort": [f"ext:{extension}:{':'.join(video_args)}"],
                    "writesubtitles": True,
                    "subtitleslangs": "all",
                }
            )

            postprocessors.append(
                {"key": "FFmpegVideoConvertor", "preferedformat": extension}
            )
            postprocessors.append(
                {"key": "FFmpegEmbedSubtitle", "already_have_subtitle": False}
            )

        # AUDIO
        elif extension in audio_args:
            ydl_opts.update(
                {
                    "format": "bestaudio/best",
                    "format_sort": [f"ext:{extension}:{':'.join(audio_args)}"],
                    "postprocessor_args": {
                        "thumbnailsconvertor+ffmpeg_o": [
                            "-c:v",
                            "png",
                            "-vf",
                            "crop=ih",
                        ]
                    },
                }
            )
            postprocessors.append(
                {
                    "key": "FFmpegExtractAudio",
                    "preferredcodec": extension,
                    "preferredquality": quality,
                    "nopostoverwrites": True,
                }
            )
            """
            # Will be a new feature, see:
            # https://github.com/yt-dlp/yt-dlp/pull/8869
            postprocessors.append(
                {
                    "key": "FFmpegSubtitlesConvertor",
                    "format": "lrc",
                    "when": "before_dl",
                }
            )
            """

        # ERROR
        else:
            raise ValueError(
                "Invalid extension type. Expected:\n"
                f"VIDEO: {', '.join(video_args)}\n"
                f"AUDIO: {', '.join(audio_args)}"
            )

        ydl_opts.update({"postprocessors": postprocessors})
        return ydl_opts

    def _prepare_tempjson(self, data: Media) -> Path:
        return self.tempdir / str(data.extractor + " " + data.id + ".info.json")

    def save_info(self, data: Media, info_dict: InfoDict) -> None:
        """Save `Media` as cached `InfoDict`"""
        file = self._prepare_tempjson(data)
        file.write_text(json.dumps(info_dict))

    def get_saved_info(self, data: Media) -> InfoDict | None:
        """Get cached `InfoDict` of a `Media` item if exist."""
        file = self._prepare_tempjson(data)
        if file.is_file():
            return json.loads(file.read_text())

    def _fetch_url(self, url: str) -> InfoDict | None:
        """Process and validate yt-dlp URLs"""

        if info := self._ydl.extract_info(url, download=False):
            # Some extractors redirect the URL to the "real URL",
            # For this extractors we need do another request.
            if info["extractor_key"] == "Generic" and info["url"] != url:
                if data := self._ydl.extract_info(info["url"], download=False):
                    info = data

            # Check if is a valid Playlist
            if entries := info.get("entries"):
                serialize = []

                for item in entries:
                    # If item has the 2 required fields, will be added.
                    if item.get("ie_key") and item.get("id"):
                        serialize.append(item)

                if not serialize:
                    return None
            # Check at least if is a valid Result
            elif not info.get("formats"):
                return None

            info = cast(InfoDict, info)
            return info
        else:
            return None

    def _info_to_dataclass(self, info: InfoDict) -> ResultType:
        # Playlist Type
        if entries := info.get("entries"):
            results = []

            # Recursive add of items
            for item in entries:
                item = self._info_to_dataclass(item)
                results.append(item)

            return Playlist(
                url=info.get("original_url") or info.get("url") or "",
                thumbnail=get_info_thumbnail(info),
                extractor=info["extractor_key"],
                id=info["id"],
                title=info.get("title") or "",
                count=info.get("playlist_count") or 0,
                entries=results,
            )

        # Single Result Type
        # Process fully and save cache copy.
        else:
            item = Media(
                url=info.get("original_url") or info.get("url") or "",
                thumbnail=get_info_thumbnail(info),
                extractor=info.get("extractor_key") or info.get("ie_key") or "",
                id=info["id"],
                title=info.get("title") or "",
                creator=info.get("uploader") or "",
                duration=info.get("duration") or 0,
            )
            if info.get("formats"):
                self.save_info(item, info)
            return item

    def extract_url(self, url: str) -> ResultType | None:
        """Extract basic information from URL.

        Args:
            url: URL to process.

        Return:
            List of `Media`.
        """

        if info := self._fetch_url(url):
            return self._info_to_dataclass(info)
        else:
            return None

    def download(
        self,
        data: Media,
        progress_callback: Callable[[dict[str, Any]], None] | None = None,
    ) -> Path:
        """Download and get the final path from a `Media` item.

        Raises:
            DownloadError: `yt-dlp` related exceptions.
        """

        # Progress Handler
        if progress_callback:
            ydl = copy(self._ydl)
            ydl._progress_hooks = [progress_callback]
        else:
            ydl = self._ydl

        # Load cached info if exist, else re-fetch info.
        if info := self.get_saved_info(data) or self._fetch_url(data.url):
            info_dict = info
        else:
            raise DownloadError("Unable to fetch info from:", data.url)

        # Start download
        try:
            info_dict = ydl.process_ie_result(info_dict, download=True)
        except DownloadError:
            raise

        final_path = Path(info_dict["requested_downloads"][0]["filepath"])
        return final_path


if __name__ == "__main__":
    from rich import print

    url = "https://gourmetdeluxxx.bandcamp.com/track/nocturnal-hooli"
    print("> Using YDL")

    ydl = YDL("temp", "m4a", quality=9)
    data = ydl.extract_url(url)
    print(data)

    if isinstance(data, Media):
        ydl.download(data)
    elif isinstance(data, Playlist):
        for item in data:
            ydl.download(item)
